import Head from "next/head";
import About from "../components/About";
import Main from "../components/Main";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import Tech from "../components/Tech";
import Script from "next/script";

export default function Home() {
  return (
    <div>
      <Head>
        <title>John | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="https://cdn.tailwindcss.com"></Script>
      </Head>
      <Navbar />
      <Main />
      <About />
      <Tech />
      <Projects />
    </div>
  );
}
